{% set name = "filetype" %}
{% set version = "1.0.2" %}
{% set sha256 = "31255843ec8b95eec26f7e08817bc42e4017659321a7d3c1818a7664f8a09aef" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - examples
    - filetype
    - filetype.types

about:
  home: https://github.com/h2non/filetype.py
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Infer file type and MIME type of any file/buffer. No external dependencies.
  description:  |
    Small and dependency free Python package to infer file type 
    and MIME type checking the magic numbers signature of a file or buffer.
    This is a Python port from filetype Go package.
  doc_url: 'https://h2non.github.io/filetype.py/'
  dev_url: 'https://github.com/h2non/filetype.py'

extra:
  recipe-maintainers: 
    - druvus
